# This workflow triggers the LMS sync whenever there is a new BSI release

name: LMS Sync

on:
  release:
    types:
      - released

jobs:
  triggerSync:
    # self-hosted doesn't work for public repos (security), so need to use ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: Brightspace/third-party-actions@actions/checkout
      with:
        fetch-depth: 0
    - name: Verify Release
      id: verify-release
      run: bash -e .github/workflows/scripts/verify-release.sh
      env:
        GITHUB_TAG: ${{ github.ref }}
        GITHUB_COMMIT_ID: ${{ github.sha }}
    - name: Install dependencies
      if: steps.verify-release.outputs.bsi-version
      run: sudo apt-get install -y curl jq
    - name: Get JWT
      id: get-jwt
      if: steps.verify-release.outputs.bsi-version
      run: bash -e .github/workflows/scripts/get-jwt.sh
      env:
        BSI_SYNC_PEM: ${{ secrets.BSI_SYNC_PEM }}
    - name: Get App Token
      id: get-app-token
      if: steps.verify-release.outputs.bsi-version
      run: bash -e .github/workflows/scripts/get-app-token.sh
      env:
        BSI_SYNC_JWT: ${{ steps.get-jwt.outputs.jwt }}
    - name: Repository Dispatch
      if: steps.verify-release.outputs.bsi-version
      uses: Brightspace/third-party-actions@actions/github-script
      with:
        script: |
          github.repos.createDispatchEvent({
            owner: 'Brightspace',
            repo: 'lms',
            event_type: 'bsi-sync',
            client_payload: {
              "bsi-version": "${{ steps.verify-release.outputs.bsi-version }}",
              "author-email": "${{ steps.verify-release.outputs.author-email }}"
            }
          });
        github-token: ${{ steps.get-app-token.outputs.token }}
